FROM jupyter/datascience-notebook

COPY jupyter_notebook_config.json /opt/conda/etc/jupyter/jupyter_notebook_config.json

USER root

# Install the icommands, curl, and wget
RUN apt-get update \
    && apt-get install -y lsb wget gnupg apt-transport-https python3.6 python-requests curl \
    && apt-get clean \
    && rm -rf /usr/lib/apt/lists/* \
    && fix-permissions $CONDA_DIR

RUN wget -qO - https://packages.irods.org/irods-signing-key.asc | apt-key add - \
    && echo "deb [arch=amd64] https://packages.irods.org/apt/ xenial main" > /etc/apt/sources.list.d/renci-irods.list \
    && apt-get update \
    && apt-get install -y irods-icommands \
    && apt-get clean \
    && rm -rf /usr/lib/apt/lists/* \
    && fix-permissions $CONDA_DIR

USER jovyan

RUN wget https://data.qiime2.org/distro/core/qiime2-2018.11-py35-linux-conda.yml

# install foundational jupyter lab
RUN conda env create -n qiime2-2018.11 --file qiime2-2018.11-py35-linux-conda.yml \
    && conda install jupyterlab=0.35.4 \
    && conda clean -tipsy \
    && fix-permissions $CONDA_DIR \
    && rm qiime2-2018.11-py35-linux-conda.yml

# install jupyter hub and extra doodads
RUN jupyter lab --version \
    && jupyter labextension install @jupyterlab/hub-extension@0.12.0 \
                                    @jupyter-widgets/jupyterlab-manager@0.38.1 \
                                    jupyterlab_bokeh@0.6.3

# Install the irods plugin for jupyter lab
RUN pip install jupyterlab_irods==2.0.1 \
    && jupyter serverextension enable --py jupyterlab_irods \
    && jupyter labextension install ijab@2.0.1

# Download and install PICRUSt2:
RUN wget https://github.com/picrust/picrust2/releases/download/v2.0.3-b/picrust2-2.0.3-b.zip
RUN unzip picrust2-2.0.3-b.zip && rm -r picrust2-2.0.3-b.zip
WORKDIR picrust2-2.0.3-b
RUN conda-env update -n qiime2-2018.11 -f picrust2-env.yaml
RUN ["/bin/bash/pip install --editable ."]
WORKDIR /home/jovyan

RUN wget https://github.com/gavinmdouglas/q2-picrust2/releases/download/v0.0.2/q2-picrust2-0.0.2.zip
RUN unzip q2-picrust2-0.0.2.zip && rm -r q2-picrust2-0.0.2.zip
WORKDIR q2-picrust2-0.0.2
RUN python setup.py install
WORKDIR /home/jovyan

#WORKDIR picrust2-2.0.3-b
#RUN pip install --editable . \
#    && python /home/jovyan/q2-picrust2-0.0.2/setup.py install
#WORKDIR /home/jovyan

ENV PATH /opt/conda/envs/qiime2-2018.11/bin/:$PATH

ENTRYPOINT ["jupyter"]

CMD ["lab", "--no-browser"] 
